title: Pranav Ninawe


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "© Makra"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: " Nothing About"
   link: "/me/" 
 - name: "CV"
   link: "Resume.pdf"
 - name: "Contact"
   link: "contact"
 
